ALTER TABLE shopping_list_items 
ADD COLUMN IF NOT EXISTS supplier_id UUID REFERENCES suppliers(id),
ADD COLUMN IF NOT EXISTS price_paid NUMERIC,
ADD COLUMN IF NOT EXISTS quantity_bought NUMERIC,
ADD COLUMN IF NOT EXISTS unit_bought TEXT,
ADD COLUMN IF NOT EXISTS price_per_unit_override NUMERIC,
ADD COLUMN IF NOT EXISTS quality_rating INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS purchase_date TIMESTAMPTZ DEFAULT NOW();
